export { default as adaptiveMain } from './adaptive-main.svg';
export { default as adaptiveDetail } from './adaptive-detail.svg';
export { default as signalMain } from './signal-main.svg';
export { default as signalDetail } from './signal-detail.svg';
export { default as researchMain } from './research-main.svg';
export { default as researchDetail } from './research-detail.svg';
export { default as agriforeCover } from './agrifore/agrifore-dashboard-clusters.png';
export { default as agriforePreview } from './agrifore/agrifore-price-prediction-result.png';
export { default as agriforeGallery1 } from './agrifore/agrifore-dashboard-trends.png';
export { default as agriforeGallery2 } from './agrifore/agrifore-market-analysis.png';
export { default as signchatCover } from './signchat/signchat-session-asl.png';
export { default as signchatPreview } from './signchat/signchat-session-bsl.png';
export { default as signchatGallery1 } from './signchat/signchat-language-selector.png';
export { default as signchatGallery2 } from './signchat/signchat-login.png';
export { default as surgemediCover } from './surgemedi/surgemedi-product-range.png';
export { default as surgemediPreview } from './surgemedi/surgemedi-about-company.png';
export { default as surgemediGallery1 } from './surgemedi/surgemedi-contact-enquiry.png';
export { default as csvSamplerCover } from './csv-sampler/csv-sampler-main-workflow.png';
export { default as csvSamplerPreview } from './csv-sampler/csv-sampler-results-log.png';
export { default as csvSamplerGallery1 } from './csv-sampler/csv-sampler-priority-config.png';
export { default as csvSamplerGallery2 } from './csv-sampler/csv-sampler-advanced-validation.png';
export { default as csvSamplerGallery3 } from './csv-sampler/csv-sampler-balance-flow.png';
export { default as csvSamplerGallery4 } from './csv-sampler/csv-sampler-save-load-config.png';
export { default as flightfinderCover } from './flightfinder-ai/lightfinder-dashboard-deaf-mute-asl.png';
export { default as flightfinderPreview } from './flightfinder-ai/flightfinder-dashboard-blind-voice.png';
export { default as flightfinderGallery1 } from './flightfinder-ai/flightfinder-dashboard-normal.png';
export { default as flightfinderGallery2 } from './flightfinder-ai/flightfinder-signup.png';
export { default as flightfinderGallery3 } from './flightfinder-ai/flightfinder-signin.png';
export { default as cropiqCover } from './crop_iq/cropiq-advisory-chat-session.png';
export { default as cropiqPreview } from './crop_iq/cropiq-dashboard-empty-state.png';
export { default as cropiqGallery1 } from './crop_iq/cropiq-advisory-quick-prompts.png';
export { default as cropiqGallery2 } from './crop_iq/cropiq-session-input-bar.png';
export { default as loanoneCover } from './loan_1/loanone-landing-hero.png';
export { default as loanonePreview } from './loan_1/loanone-guided-signup.png';
export { default as loanoneGallery1 } from './loan_1/loanone-features-flow.png';
export { default as loanoneGallery2 } from './loan_1/loanone-loan-application-step.png';
export { default as loanoneGallery3 } from './loan_1/loanone-footer-cta.png';
export { default as forecastingToolCover } from './R_Studio_ARIMA-Prophet/forecasting-tool-overview.png';
export { default as forecastingToolPreview } from './R_Studio_ARIMA-Prophet/forecasting-tool-model-training.png';
export { default as forecastingToolGallery1 } from './R_Studio_ARIMA-Prophet/forecasting-tool-eda-encoded-data.png';
export { default as forecastingToolGallery2 } from './R_Studio_ARIMA-Prophet/forecasting-tool-arima-prophet-panel.png';
export { default as forecastingToolGallery3 } from './R_Studio_ARIMA-Prophet/forecasting-tool-sidebar-controls.png';
export { default as movieRecCover } from './Collaborative Filtering Recommendation Engine/movie-rec-engine-discovery-grid.png';
export { default as movieRecPreview } from './Collaborative Filtering Recommendation Engine/movie-rec-engine-recommendation-panel.png';
export { default as movieRecGallery1 } from './Collaborative Filtering Recommendation Engine/movie-rec-engine-previously-watched.png';
export { default as movieRecGallery2 } from './Collaborative Filtering Recommendation Engine/movie-rec-engine-ranked-recommendations.png';


